service: bidscale
plugins:
  - serverless-offline
  - serverless-dynamodb-local
provider:
  name: aws
  runtime: nodejs14.x
  stage: test
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:GetItem"
        - "dynamodb:Scan"
        - "dynamodb:BatchWriteItem"
      Resource:
        - "arn:aws:dynamodb:us-east-1:578957942104:table/warehouse"
        - "arn:aws:dynamodb:us-east-1:578957942104:table/product"
        - "arn:aws:dynamodb:us-east-1:578957942104:table/inventory"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::bidscale/*"
functions:
  uploadCsv:
    handler: server/functions/Upload.upload
    events:
      - http:
          path: upload
          method: post
          cors: true
  getProductValue:
    handler: server/functions/GetProductValue.getProductValue
    events:
      - http:
          path: product/value
          method: get
          cors: true
  getProductInventories:
    handler: server/functions/GetProductInventories.getProductInventories
    events:
      - http:
          path: product/inventories
          method: get
          cors: true